#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ParamSection {
    Macro,
    Oscillator1,
    Oscillator2,
    Sub,
    Mixer,
    Filter,
    AmpEnvelope,
    FilterEnvelope,
    Voice,
    FinalStage,
    Chorus,
    Reverb,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ParamUnit {
    Normalized,
    Hertz,
    Milliseconds,
    Cents,
    Semitones,
    Decibels,
    Boolean,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ParamSpec {
    pub id: ParamId,
    pub key: &'static str,
    pub name: &'static str,
    pub section: ParamSection,
    pub default: f32,
    pub min: f32,
    pub max: f32,
    pub unit: ParamUnit,
    pub host_visible: bool,
    pub macro_id: Option<MacroId>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(usize)]
pub enum MacroId {
    Gravitacija = 0,
    Bloom = 1,
    Heat = 2,
    Ruin = 3,
    Swarm = 4,
}

impl MacroId {
    pub const ALL: [Self; 5] = [
        Self::Gravitacija,
        Self::Bloom,
        Self::Heat,
        Self::Ruin,
        Self::Swarm,
    ];

    pub const fn key(self) -> &'static str {
        match self {
            Self::Gravitacija => "gravitacija",
            Self::Bloom => "bloom",
            Self::Heat => "heat",
            Self::Ruin => "ruin",
            Self::Swarm => "swarm",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(usize)]
pub enum ParamId {
    GravitacijaMacro = 0,
    BloomMacro = 1,
    HeatMacro = 2,
    RuinMacro = 3,
    SwarmMacro = 4,
    Osc1SawLevel = 5,
    Osc1PulseLevel = 6,
    Osc1TriangleLevel = 7,
    Osc1NoiseLevel = 8,
    Osc1FineTuneCents = 9,
    Osc2SawLevel = 10,
    Osc2PulseLevel = 11,
    Osc2TriangleLevel = 12,
    Osc2IntervalSemitones = 13,
    Osc2FineTuneCents = 14,
    Osc2SyncAmount = 15,
    Osc2CrossmodAmount = 16,
    SubLevel = 17,
    SubOctaveOffset = 18,
    MixerPreFilterDrive = 19,
    MixerBodyMix = 20,
    FilterCutoffHz = 21,
    FilterResonance = 22,
    FilterDrive = 23,
    FilterKeytrack = 24,
    AmpEnvAttackMs = 25,
    AmpEnvDecayMs = 26,
    AmpEnvSustain = 27,
    AmpEnvReleaseMs = 28,
    FilterEnvAttackMs = 29,
    FilterEnvDecayMs = 30,
    FilterEnvSustain = 31,
    FilterEnvReleaseMs = 32,
    FilterEnvDepth = 33,
    VoiceStereoWidth = 34,
    VoiceDetuneSpreadCents = 35,
    VoiceVelocityToLevel = 36,
    VoiceVelocityToFilter = 37,
    FinalStageBodyDrive = 38,
    FinalStageAsymmetry = 39,
    FinalStageLowMidEmphasis = 40,
    FinalStageOutputTrimDb = 41,
    ChorusEnabled = 42,
    ChorusMix = 43,
    ChorusDepth = 44,
    ChorusRateHz = 45,
    ReverbEnabled = 46,
    ReverbMix = 47,
    ReverbSize = 48,
    ReverbDamping = 49,
}

const fn spec(
    id: ParamId,
    key: &'static str,
    name: &'static str,
    section: ParamSection,
    default: f32,
    min: f32,
    max: f32,
    unit: ParamUnit,
    host_visible: bool,
    macro_id: Option<MacroId>,
) -> ParamSpec {
    ParamSpec {
        id,
        key,
        name,
        section,
        default,
        min,
        max,
        unit,
        host_visible,
        macro_id,
    }
}

const PARAM_SPECS: [ParamSpec; 50] = [
    spec(
        ParamId::GravitacijaMacro,
        "gravitacija",
        "Gravitacija",
        ParamSection::Macro,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        Some(MacroId::Gravitacija),
    ),
    spec(
        ParamId::BloomMacro,
        "bloom",
        "Bloom",
        ParamSection::Macro,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        Some(MacroId::Bloom),
    ),
    spec(
        ParamId::HeatMacro,
        "heat",
        "Heat",
        ParamSection::Macro,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        Some(MacroId::Heat),
    ),
    spec(
        ParamId::RuinMacro,
        "ruin",
        "Ruin",
        ParamSection::Macro,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        Some(MacroId::Ruin),
    ),
    spec(
        ParamId::SwarmMacro,
        "swarm",
        "Swarm",
        ParamSection::Macro,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        Some(MacroId::Swarm),
    ),
    spec(
        ParamId::Osc1SawLevel,
        "osc1_saw_level",
        "Osc1 Saw Level",
        ParamSection::Oscillator1,
        0.70,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::Osc1PulseLevel,
        "osc1_pulse_level",
        "Osc1 Pulse Level",
        ParamSection::Oscillator1,
        0.25,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::Osc1TriangleLevel,
        "osc1_triangle_level",
        "Osc1 Triangle Level",
        ParamSection::Oscillator1,
        0.10,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::Osc1NoiseLevel,
        "osc1_noise_level",
        "Osc1 Noise Level",
        ParamSection::Oscillator1,
        0.00,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::Osc1FineTuneCents,
        "osc1_fine_tune_cents",
        "Osc1 Fine Tune",
        ParamSection::Oscillator1,
        0.0,
        -100.0,
        100.0,
        ParamUnit::Cents,
        true,
        None,
    ),
    spec(
        ParamId::Osc2SawLevel,
        "osc2_saw_level",
        "Osc2 Saw Level",
        ParamSection::Oscillator2,
        0.45,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::Osc2PulseLevel,
        "osc2_pulse_level",
        "Osc2 Pulse Level",
        ParamSection::Oscillator2,
        0.20,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::Osc2TriangleLevel,
        "osc2_triangle_level",
        "Osc2 Triangle Level",
        ParamSection::Oscillator2,
        0.00,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::Osc2IntervalSemitones,
        "osc2_interval_semitones",
        "Osc2 Interval",
        ParamSection::Oscillator2,
        0.0,
        -24.0,
        24.0,
        ParamUnit::Semitones,
        true,
        None,
    ),
    spec(
        ParamId::Osc2FineTuneCents,
        "osc2_fine_tune_cents",
        "Osc2 Fine Tune",
        ParamSection::Oscillator2,
        0.0,
        -100.0,
        100.0,
        ParamUnit::Cents,
        true,
        None,
    ),
    spec(
        ParamId::Osc2SyncAmount,
        "osc2_sync_amount",
        "Osc2 Sync",
        ParamSection::Oscillator2,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::Osc2CrossmodAmount,
        "osc2_crossmod_amount",
        "Osc2 Crossmod",
        ParamSection::Oscillator2,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::SubLevel,
        "sub_level",
        "Sub Level",
        ParamSection::Sub,
        0.35,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::SubOctaveOffset,
        "sub_octave_offset",
        "Sub Octave Offset",
        ParamSection::Sub,
        -1.0,
        -2.0,
        0.0,
        ParamUnit::Semitones,
        true,
        None,
    ),
    spec(
        ParamId::MixerPreFilterDrive,
        "mixer_pre_filter_drive",
        "Pre-Filter Drive",
        ParamSection::Mixer,
        0.28,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::MixerBodyMix,
        "mixer_body_mix",
        "Body Mix",
        ParamSection::Mixer,
        0.40,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::FilterCutoffHz,
        "filter_cutoff_hz",
        "Filter Cutoff",
        ParamSection::Filter,
        4_200.0,
        20.0,
        20_000.0,
        ParamUnit::Hertz,
        true,
        None,
    ),
    spec(
        ParamId::FilterResonance,
        "filter_resonance",
        "Filter Resonance",
        ParamSection::Filter,
        0.22,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::FilterDrive,
        "filter_drive",
        "Filter Drive",
        ParamSection::Filter,
        0.18,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::FilterKeytrack,
        "filter_keytrack",
        "Filter Keytrack",
        ParamSection::Filter,
        0.45,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::AmpEnvAttackMs,
        "amp_env_attack_ms",
        "Amp Attack",
        ParamSection::AmpEnvelope,
        25.0,
        1.0,
        10_000.0,
        ParamUnit::Milliseconds,
        true,
        None,
    ),
    spec(
        ParamId::AmpEnvDecayMs,
        "amp_env_decay_ms",
        "Amp Decay",
        ParamSection::AmpEnvelope,
        380.0,
        1.0,
        10_000.0,
        ParamUnit::Milliseconds,
        true,
        None,
    ),
    spec(
        ParamId::AmpEnvSustain,
        "amp_env_sustain",
        "Amp Sustain",
        ParamSection::AmpEnvelope,
        0.82,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::AmpEnvReleaseMs,
        "amp_env_release_ms",
        "Amp Release",
        ParamSection::AmpEnvelope,
        760.0,
        1.0,
        10_000.0,
        ParamUnit::Milliseconds,
        true,
        None,
    ),
    spec(
        ParamId::FilterEnvAttackMs,
        "filter_env_attack_ms",
        "Filter Env Attack",
        ParamSection::FilterEnvelope,
        40.0,
        1.0,
        10_000.0,
        ParamUnit::Milliseconds,
        true,
        None,
    ),
    spec(
        ParamId::FilterEnvDecayMs,
        "filter_env_decay_ms",
        "Filter Env Decay",
        ParamSection::FilterEnvelope,
        420.0,
        1.0,
        10_000.0,
        ParamUnit::Milliseconds,
        true,
        None,
    ),
    spec(
        ParamId::FilterEnvSustain,
        "filter_env_sustain",
        "Filter Env Sustain",
        ParamSection::FilterEnvelope,
        0.45,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::FilterEnvReleaseMs,
        "filter_env_release_ms",
        "Filter Env Release",
        ParamSection::FilterEnvelope,
        820.0,
        1.0,
        10_000.0,
        ParamUnit::Milliseconds,
        true,
        None,
    ),
    spec(
        ParamId::FilterEnvDepth,
        "filter_env_depth",
        "Filter Env Depth",
        ParamSection::FilterEnvelope,
        0.52,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::VoiceStereoWidth,
        "voice_stereo_width",
        "Stereo Width",
        ParamSection::Voice,
        0.68,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::VoiceDetuneSpreadCents,
        "voice_detune_spread_cents",
        "Detune Spread",
        ParamSection::Voice,
        10.0,
        0.0,
        50.0,
        ParamUnit::Cents,
        true,
        None,
    ),
    spec(
        ParamId::VoiceVelocityToLevel,
        "voice_velocity_to_level",
        "Velocity To Level",
        ParamSection::Voice,
        0.35,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::VoiceVelocityToFilter,
        "voice_velocity_to_filter",
        "Velocity To Filter",
        ParamSection::Voice,
        0.25,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::FinalStageBodyDrive,
        "final_stage_body_drive",
        "Final Stage Body Drive",
        ParamSection::FinalStage,
        0.30,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::FinalStageAsymmetry,
        "final_stage_asymmetry",
        "Final Stage Asymmetry",
        ParamSection::FinalStage,
        0.12,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::FinalStageLowMidEmphasis,
        "final_stage_low_mid_emphasis",
        "Low Mid Emphasis",
        ParamSection::FinalStage,
        0.42,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::FinalStageOutputTrimDb,
        "final_stage_output_trim_db",
        "Output Trim",
        ParamSection::FinalStage,
        -3.0,
        -24.0,
        12.0,
        ParamUnit::Decibels,
        true,
        None,
    ),
    spec(
        ParamId::ChorusEnabled,
        "chorus_enabled",
        "Chorus Enabled",
        ParamSection::Chorus,
        1.0,
        0.0,
        1.0,
        ParamUnit::Boolean,
        true,
        None,
    ),
    spec(
        ParamId::ChorusMix,
        "chorus_mix",
        "Chorus Mix",
        ParamSection::Chorus,
        0.20,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::ChorusDepth,
        "chorus_depth",
        "Chorus Depth",
        ParamSection::Chorus,
        0.35,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::ChorusRateHz,
        "chorus_rate_hz",
        "Chorus Rate",
        ParamSection::Chorus,
        0.25,
        0.01,
        20.0,
        ParamUnit::Hertz,
        true,
        None,
    ),
    spec(
        ParamId::ReverbEnabled,
        "reverb_enabled",
        "Reverb Enabled",
        ParamSection::Reverb,
        1.0,
        0.0,
        1.0,
        ParamUnit::Boolean,
        true,
        None,
    ),
    spec(
        ParamId::ReverbMix,
        "reverb_mix",
        "Reverb Mix",
        ParamSection::Reverb,
        0.16,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::ReverbSize,
        "reverb_size",
        "Reverb Size",
        ParamSection::Reverb,
        0.52,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::ReverbDamping,
        "reverb_damping",
        "Reverb Damping",
        ParamSection::Reverb,
        0.40,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
];

pub fn all_params() -> &'static [ParamSpec] {
    &PARAM_SPECS
}

pub const fn macro_param_id(macro_id: MacroId) -> ParamId {
    match macro_id {
        MacroId::Gravitacija => ParamId::GravitacijaMacro,
        MacroId::Bloom => ParamId::BloomMacro,
        MacroId::Heat => ParamId::HeatMacro,
        MacroId::Ruin => ParamId::RuinMacro,
        MacroId::Swarm => ParamId::SwarmMacro,
    }
}

pub fn param_spec(id: ParamId) -> &'static ParamSpec {
    &PARAM_SPECS[id as usize]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn macro_specs_round_trip() {
        for macro_id in MacroId::ALL {
            let spec = param_spec(macro_param_id(macro_id));
            assert_eq!(spec.macro_id, Some(macro_id));
            assert_eq!(spec.key, macro_id.key());
        }
    }

    #[test]
    fn registry_order_matches_ids() {
        for (index, spec) in all_params().iter().enumerate() {
            assert_eq!(spec.id as usize, index);
        }
    }
}
