#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ParamSection {
    Macro,
    Oscillator1,
    Oscillator2,
    Spectral,
    Source,
    Sub,
    Mixer,
    Filter,
    AmpEnvelope,
    FilterEnvelope,
    Voice,
    Performance,
    FinalStage,
    Chorus,
    Reverb,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ParamUnit {
    Normalized,
    Hertz,
    Milliseconds,
    Cents,
    Semitones,
    Decibels,
    Boolean,
    Indexed,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ParamSpec {
    pub id: ParamId,
    pub key: &'static str,
    pub name: &'static str,
    pub section: ParamSection,
    pub default: f32,
    pub min: f32,
    pub max: f32,
    pub unit: ParamUnit,
    pub host_visible: bool,
    pub macro_id: Option<MacroId>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(usize)]
pub enum MacroId {
    Gravitacija = 0,
    Bloom = 1,
    Heat = 2,
    Ruin = 3,
    Swarm = 4,
}

impl MacroId {
    pub const ALL: [Self; 5] = [
        Self::Gravitacija,
        Self::Bloom,
        Self::Heat,
        Self::Ruin,
        Self::Swarm,
    ];

    pub const fn key(self) -> &'static str {
        match self {
            Self::Gravitacija => "gravitacija",
            Self::Bloom => "bloom",
            Self::Heat => "heat",
            Self::Ruin => "ruin",
            Self::Swarm => "swarm",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(usize)]
pub enum ParamId {
    GravitacijaMacro = 0,
    BloomMacro = 1,
    HeatMacro = 2,
    RuinMacro = 3,
    SwarmMacro = 4,
    Osc1SawLevel = 5,
    Osc1PulseLevel = 6,
    Osc1TriangleLevel = 7,
    Osc1NoiseLevel = 8,
    Osc1FineTuneCents = 9,
    Osc2SawLevel = 10,
    Osc2PulseLevel = 11,
    Osc2TriangleLevel = 12,
    Osc2IntervalSemitones = 13,
    Osc2FineTuneCents = 14,
    Osc2SyncAmount = 15,
    Osc2CrossmodAmount = 16,
    SubLevel = 17,
    SubOctaveOffset = 18,
    MixerPreFilterDrive = 19,
    MixerBodyMix = 20,
    FilterCutoffHz = 21,
    FilterResonance = 22,
    FilterDrive = 23,
    FilterKeytrack = 24,
    AmpEnvAttackMs = 25,
    AmpEnvDecayMs = 26,
    AmpEnvSustain = 27,
    AmpEnvReleaseMs = 28,
    FilterEnvAttackMs = 29,
    FilterEnvDecayMs = 30,
    FilterEnvSustain = 31,
    FilterEnvReleaseMs = 32,
    FilterEnvDepth = 33,
    VoiceStereoWidth = 34,
    VoiceDetuneSpreadCents = 35,
    VoiceVelocityToLevel = 36,
    VoiceVelocityToFilter = 37,
    FinalStageBodyDrive = 38,
    FinalStageAsymmetry = 39,
    FinalStageLowMidEmphasis = 40,
    FinalStageOutputTrimDb = 41,
    ChorusEnabled = 42,
    ChorusMix = 43,
    ChorusDepth = 44,
    ChorusRateHz = 45,
    ReverbEnabled = 46,
    ReverbMix = 47,
    ReverbSize = 48,
    ReverbDamping = 49,
    PerformanceVelocityToLevel = 50,
    PerformanceVelocityToFilter = 51,
    PerformanceAftertouchToGravitacija = 52,
    PerformanceAftertouchToBaklja = 53,
    PerformanceModWheelToBloom = 54,
    PerformanceModWheelToSwarm = 55,
    Osc1PulseWidth = 56,
    Osc1PwmDepth = 57,
    Osc2PulseWidth = 58,
    Osc2PwmDepth = 59,
    SourcePwmRateHz = 60,
    Osc1PhaseMode = 61,
    Osc1StartPhase = 62,
    Osc2PhaseMode = 63,
    Osc2StartPhase = 64,
    Osc2Level = 65,
    Osc2PitchMode = 66,
    Osc2Ratio = 67,
    NoiseColor = 68,
    NoiseFilterLevel = 69,
    NoiseBodyLevel = 70,
    Osc1SawBend = 71,
    Osc2SawBend = 72,
    Osc1TriangleFold = 73,
    Osc2TriangleFold = 74,
    Osc1PulseEdge = 75,
    Osc2PulseEdge = 76,
    AnalogDrift = 77,
    MicroJitter = 78,
    FmAmount = 79,
    FmDirection = 80,
    PhaseModAmount = 81,
    PhaseModDirection = 82,
    RingModAmount = 83,
    AmAmount = 84,
    SyncDirection = 85,
    SyncSoftness = 86,
    CrossMixMode = 87,
    CrossMixAmount = 88,
    SpectralLevel = 89,
    SpectralTable = 90,
    SpectralPosition = 91,
    SpectralMorph = 92,
    SpectralRatio = 93,
    SpectralFineTuneCents = 94,
    AdditiveLevel = 95,
    AdditivePartialCount = 96,
    AdditiveHarmonicSpread = 97,
    AdditiveOddEvenBalance = 98,
    AdditiveInharmonicity = 99,
    AdditiveSpectralTilt = 100,
    AdditiveRandomDetuneCents = 101,
    Osc1Bandlimit = 102,
    Osc2Bandlimit = 103,
}

#[allow(clippy::too_many_arguments)]
const fn spec(
    id: ParamId,
    key: &'static str,
    name: &'static str,
    section: ParamSection,
    default: f32,
    min: f32,
    max: f32,
    unit: ParamUnit,
    host_visible: bool,
    macro_id: Option<MacroId>,
) -> ParamSpec {
    ParamSpec {
        id,
        key,
        name,
        section,
        default,
        min,
        max,
        unit,
        host_visible,
        macro_id,
    }
}

const PARAM_SPECS: [ParamSpec; 104] = [
    spec(
        ParamId::GravitacijaMacro,
        "gravitacija",
        "Gravitacija",
        ParamSection::Macro,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        Some(MacroId::Gravitacija),
    ),
    spec(
        ParamId::BloomMacro,
        "bloom",
        "Bloom",
        ParamSection::Macro,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        Some(MacroId::Bloom),
    ),
    spec(
        ParamId::HeatMacro,
        "heat",
        "Heat",
        ParamSection::Macro,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        Some(MacroId::Heat),
    ),
    spec(
        ParamId::RuinMacro,
        "ruin",
        "Ruin",
        ParamSection::Macro,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        Some(MacroId::Ruin),
    ),
    spec(
        ParamId::SwarmMacro,
        "swarm",
        "Swarm",
        ParamSection::Macro,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        Some(MacroId::Swarm),
    ),
    spec(
        ParamId::Osc1SawLevel,
        "osc1_saw_level",
        "Osc1 Saw Level",
        ParamSection::Oscillator1,
        0.70,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::Osc1PulseLevel,
        "osc1_pulse_level",
        "Osc1 Pulse Level",
        ParamSection::Oscillator1,
        0.25,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::Osc1TriangleLevel,
        "osc1_triangle_level",
        "Osc1 Triangle Level",
        ParamSection::Oscillator1,
        0.10,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::Osc1NoiseLevel,
        "osc1_noise_level",
        "Osc1 Noise Level",
        ParamSection::Oscillator1,
        0.00,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::Osc1FineTuneCents,
        "osc1_fine_tune_cents",
        "Osc1 Fine Tune",
        ParamSection::Oscillator1,
        0.0,
        -100.0,
        100.0,
        ParamUnit::Cents,
        true,
        None,
    ),
    spec(
        ParamId::Osc2SawLevel,
        "osc2_saw_level",
        "Osc2 Saw Level",
        ParamSection::Oscillator2,
        0.45,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::Osc2PulseLevel,
        "osc2_pulse_level",
        "Osc2 Pulse Level",
        ParamSection::Oscillator2,
        0.20,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::Osc2TriangleLevel,
        "osc2_triangle_level",
        "Osc2 Triangle Level",
        ParamSection::Oscillator2,
        0.00,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::Osc2IntervalSemitones,
        "osc2_interval_semitones",
        "Osc2 Interval",
        ParamSection::Oscillator2,
        0.0,
        -24.0,
        24.0,
        ParamUnit::Semitones,
        true,
        None,
    ),
    spec(
        ParamId::Osc2FineTuneCents,
        "osc2_fine_tune_cents",
        "Osc2 Fine Tune",
        ParamSection::Oscillator2,
        0.0,
        -100.0,
        100.0,
        ParamUnit::Cents,
        true,
        None,
    ),
    spec(
        ParamId::Osc2SyncAmount,
        "osc2_sync_amount",
        "Osc2 Sync",
        ParamSection::Oscillator2,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::Osc2CrossmodAmount,
        "osc2_crossmod_amount",
        "Osc2 Crossmod",
        ParamSection::Oscillator2,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::SubLevel,
        "sub_level",
        "Sub Level",
        ParamSection::Sub,
        0.35,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::SubOctaveOffset,
        "sub_octave_offset",
        "Sub Octave Offset",
        ParamSection::Sub,
        -1.0,
        -2.0,
        0.0,
        ParamUnit::Semitones,
        true,
        None,
    ),
    spec(
        ParamId::MixerPreFilterDrive,
        "mixer_pre_filter_drive",
        "Pre-Filter Drive",
        ParamSection::Mixer,
        0.28,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::MixerBodyMix,
        "mixer_body_mix",
        "Body Mix",
        ParamSection::Mixer,
        0.40,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::FilterCutoffHz,
        "filter_cutoff_hz",
        "Filter Cutoff",
        ParamSection::Filter,
        4_200.0,
        20.0,
        20_000.0,
        ParamUnit::Hertz,
        true,
        None,
    ),
    spec(
        ParamId::FilterResonance,
        "filter_resonance",
        "Filter Resonance",
        ParamSection::Filter,
        0.22,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::FilterDrive,
        "filter_drive",
        "Filter Drive",
        ParamSection::Filter,
        0.18,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::FilterKeytrack,
        "filter_keytrack",
        "Filter Keytrack",
        ParamSection::Filter,
        0.45,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::AmpEnvAttackMs,
        "amp_env_attack_ms",
        "Amp Attack",
        ParamSection::AmpEnvelope,
        25.0,
        1.0,
        10_000.0,
        ParamUnit::Milliseconds,
        true,
        None,
    ),
    spec(
        ParamId::AmpEnvDecayMs,
        "amp_env_decay_ms",
        "Amp Decay",
        ParamSection::AmpEnvelope,
        380.0,
        1.0,
        10_000.0,
        ParamUnit::Milliseconds,
        true,
        None,
    ),
    spec(
        ParamId::AmpEnvSustain,
        "amp_env_sustain",
        "Amp Sustain",
        ParamSection::AmpEnvelope,
        0.82,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::AmpEnvReleaseMs,
        "amp_env_release_ms",
        "Amp Release",
        ParamSection::AmpEnvelope,
        760.0,
        1.0,
        10_000.0,
        ParamUnit::Milliseconds,
        true,
        None,
    ),
    spec(
        ParamId::FilterEnvAttackMs,
        "filter_env_attack_ms",
        "Filter Env Attack",
        ParamSection::FilterEnvelope,
        40.0,
        1.0,
        10_000.0,
        ParamUnit::Milliseconds,
        true,
        None,
    ),
    spec(
        ParamId::FilterEnvDecayMs,
        "filter_env_decay_ms",
        "Filter Env Decay",
        ParamSection::FilterEnvelope,
        420.0,
        1.0,
        10_000.0,
        ParamUnit::Milliseconds,
        true,
        None,
    ),
    spec(
        ParamId::FilterEnvSustain,
        "filter_env_sustain",
        "Filter Env Sustain",
        ParamSection::FilterEnvelope,
        0.45,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::FilterEnvReleaseMs,
        "filter_env_release_ms",
        "Filter Env Release",
        ParamSection::FilterEnvelope,
        820.0,
        1.0,
        10_000.0,
        ParamUnit::Milliseconds,
        true,
        None,
    ),
    spec(
        ParamId::FilterEnvDepth,
        "filter_env_depth",
        "Filter Env Depth",
        ParamSection::FilterEnvelope,
        0.52,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::VoiceStereoWidth,
        "voice_stereo_width",
        "Stereo Width",
        ParamSection::Voice,
        0.68,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::VoiceDetuneSpreadCents,
        "voice_detune_spread_cents",
        "Detune Spread",
        ParamSection::Voice,
        10.0,
        0.0,
        50.0,
        ParamUnit::Cents,
        true,
        None,
    ),
    spec(
        ParamId::VoiceVelocityToLevel,
        "voice_velocity_to_level",
        "Velocity To Level",
        ParamSection::Voice,
        0.35,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::VoiceVelocityToFilter,
        "voice_velocity_to_filter",
        "Velocity To Filter",
        ParamSection::Voice,
        0.25,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::FinalStageBodyDrive,
        "final_stage_body_drive",
        "Final Stage Body Drive",
        ParamSection::FinalStage,
        0.30,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::FinalStageAsymmetry,
        "final_stage_asymmetry",
        "Final Stage Asymmetry",
        ParamSection::FinalStage,
        0.12,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::FinalStageLowMidEmphasis,
        "final_stage_low_mid_emphasis",
        "Low Mid Emphasis",
        ParamSection::FinalStage,
        0.42,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::FinalStageOutputTrimDb,
        "final_stage_output_trim_db",
        "Output Trim",
        ParamSection::FinalStage,
        -3.0,
        -24.0,
        12.0,
        ParamUnit::Decibels,
        true,
        None,
    ),
    spec(
        ParamId::ChorusEnabled,
        "chorus_enabled",
        "Chorus Enabled",
        ParamSection::Chorus,
        1.0,
        0.0,
        1.0,
        ParamUnit::Boolean,
        true,
        None,
    ),
    spec(
        ParamId::ChorusMix,
        "chorus_mix",
        "Chorus Mix",
        ParamSection::Chorus,
        0.20,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::ChorusDepth,
        "chorus_depth",
        "Chorus Depth",
        ParamSection::Chorus,
        0.35,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::ChorusRateHz,
        "chorus_rate_hz",
        "Chorus Rate",
        ParamSection::Chorus,
        0.25,
        0.01,
        20.0,
        ParamUnit::Hertz,
        true,
        None,
    ),
    spec(
        ParamId::ReverbEnabled,
        "reverb_enabled",
        "Reverb Enabled",
        ParamSection::Reverb,
        1.0,
        0.0,
        1.0,
        ParamUnit::Boolean,
        true,
        None,
    ),
    spec(
        ParamId::ReverbMix,
        "reverb_mix",
        "Reverb Mix",
        ParamSection::Reverb,
        0.16,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::ReverbSize,
        "reverb_size",
        "Reverb Size",
        ParamSection::Reverb,
        0.52,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::ReverbDamping,
        "reverb_damping",
        "Reverb Damping",
        ParamSection::Reverb,
        0.40,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::PerformanceVelocityToLevel,
        "performance_velocity_to_level",
        "Performance Velocity To Level",
        ParamSection::Performance,
        0.20,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::PerformanceVelocityToFilter,
        "performance_velocity_to_filter",
        "Performance Velocity To Filter",
        ParamSection::Performance,
        0.20,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::PerformanceAftertouchToGravitacija,
        "performance_aftertouch_to_gravitacija",
        "Aftertouch To Gravitacija",
        ParamSection::Performance,
        0.20,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::PerformanceAftertouchToBaklja,
        "performance_aftertouch_to_baklja",
        "Aftertouch To Baklja",
        ParamSection::Performance,
        0.20,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::PerformanceModWheelToBloom,
        "performance_mod_wheel_to_bloom",
        "Mod Wheel To Bloom",
        ParamSection::Performance,
        0.20,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::PerformanceModWheelToSwarm,
        "performance_mod_wheel_to_swarm",
        "Mod Wheel To Swarm",
        ParamSection::Performance,
        0.20,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::Osc1PulseWidth,
        "osc1_pulse_width",
        "Osc1 Pulse Width",
        ParamSection::Oscillator1,
        0.5,
        0.05,
        0.95,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::Osc1PwmDepth,
        "osc1_pwm_depth",
        "Osc1 PWM Depth",
        ParamSection::Oscillator1,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::Osc2PulseWidth,
        "osc2_pulse_width",
        "Osc2 Pulse Width",
        ParamSection::Oscillator2,
        0.5,
        0.05,
        0.95,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::Osc2PwmDepth,
        "osc2_pwm_depth",
        "Osc2 PWM Depth",
        ParamSection::Oscillator2,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::SourcePwmRateHz,
        "source_pwm_rate_hz",
        "PWM Rate",
        ParamSection::Source,
        0.35,
        0.01,
        20.0,
        ParamUnit::Hertz,
        true,
        None,
    ),
    spec(
        ParamId::Osc1PhaseMode,
        "osc1_phase_mode",
        "Osc1 Phase Mode",
        ParamSection::Oscillator1,
        0.0,
        0.0,
        2.0,
        ParamUnit::Indexed,
        true,
        None,
    ),
    spec(
        ParamId::Osc1StartPhase,
        "osc1_start_phase",
        "Osc1 Start Phase",
        ParamSection::Oscillator1,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::Osc2PhaseMode,
        "osc2_phase_mode",
        "Osc2 Phase Mode",
        ParamSection::Oscillator2,
        0.0,
        0.0,
        2.0,
        ParamUnit::Indexed,
        true,
        None,
    ),
    spec(
        ParamId::Osc2StartPhase,
        "osc2_start_phase",
        "Osc2 Start Phase",
        ParamSection::Oscillator2,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::Osc2Level,
        "osc2_level",
        "Osc2 Level",
        ParamSection::Oscillator2,
        1.0,
        0.0,
        2.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::Osc2PitchMode,
        "osc2_pitch_mode",
        "Osc2 Pitch Mode",
        ParamSection::Oscillator2,
        0.0,
        0.0,
        1.0,
        ParamUnit::Indexed,
        true,
        None,
    ),
    spec(
        ParamId::Osc2Ratio,
        "osc2_ratio",
        "Osc2 Ratio",
        ParamSection::Oscillator2,
        1.0,
        0.25,
        4.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::NoiseColor,
        "noise_color",
        "Noise Color",
        ParamSection::Source,
        0.0,
        0.0,
        3.0,
        ParamUnit::Indexed,
        true,
        None,
    ),
    spec(
        ParamId::NoiseFilterLevel,
        "noise_filter_level",
        "Noise To Filter",
        ParamSection::Source,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::NoiseBodyLevel,
        "noise_body_level",
        "Noise To Body",
        ParamSection::Source,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::Osc1SawBend,
        "osc1_saw_bend",
        "Osc1 Saw Bend",
        ParamSection::Oscillator1,
        0.0,
        -1.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::Osc2SawBend,
        "osc2_saw_bend",
        "Osc2 Saw Bend",
        ParamSection::Oscillator2,
        0.0,
        -1.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::Osc1TriangleFold,
        "osc1_triangle_fold",
        "Osc1 Triangle Fold",
        ParamSection::Oscillator1,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::Osc2TriangleFold,
        "osc2_triangle_fold",
        "Osc2 Triangle Fold",
        ParamSection::Oscillator2,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::Osc1PulseEdge,
        "osc1_pulse_edge",
        "Osc1 Pulse Edge",
        ParamSection::Oscillator1,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::Osc2PulseEdge,
        "osc2_pulse_edge",
        "Osc2 Pulse Edge",
        ParamSection::Oscillator2,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::AnalogDrift,
        "analog_drift",
        "Analog Drift",
        ParamSection::Source,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::MicroJitter,
        "micro_jitter",
        "Micro Jitter",
        ParamSection::Source,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::FmAmount,
        "fm_amount",
        "FM Amount",
        ParamSection::Source,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::FmDirection,
        "fm_direction",
        "FM Direction",
        ParamSection::Source,
        0.0,
        0.0,
        1.0,
        ParamUnit::Indexed,
        true,
        None,
    ),
    spec(
        ParamId::PhaseModAmount,
        "phase_mod_amount",
        "Phase Mod Amount",
        ParamSection::Source,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::PhaseModDirection,
        "phase_mod_direction",
        "Phase Mod Direction",
        ParamSection::Source,
        0.0,
        0.0,
        1.0,
        ParamUnit::Indexed,
        true,
        None,
    ),
    spec(
        ParamId::RingModAmount,
        "ring_mod_amount",
        "Ring Mod Amount",
        ParamSection::Source,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::AmAmount,
        "am_amount",
        "AM Amount",
        ParamSection::Source,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::SyncDirection,
        "sync_direction",
        "Sync Direction",
        ParamSection::Source,
        0.0,
        0.0,
        1.0,
        ParamUnit::Indexed,
        true,
        None,
    ),
    spec(
        ParamId::SyncSoftness,
        "sync_softness",
        "Sync Softness",
        ParamSection::Source,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::CrossMixMode,
        "cross_mix_mode",
        "Cross Mix Mode",
        ParamSection::Source,
        0.0,
        0.0,
        4.0,
        ParamUnit::Indexed,
        true,
        None,
    ),
    spec(
        ParamId::CrossMixAmount,
        "cross_mix_amount",
        "Cross Mix Amount",
        ParamSection::Source,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::SpectralLevel,
        "spectral_level",
        "Spectral Level",
        ParamSection::Spectral,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::SpectralTable,
        "spectral_table",
        "Spectral Table",
        ParamSection::Spectral,
        0.0,
        0.0,
        4.0,
        ParamUnit::Indexed,
        true,
        None,
    ),
    spec(
        ParamId::SpectralPosition,
        "spectral_position",
        "Spectral Position",
        ParamSection::Spectral,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::SpectralMorph,
        "spectral_morph",
        "Spectral Morph",
        ParamSection::Spectral,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::SpectralRatio,
        "spectral_ratio",
        "Spectral Ratio",
        ParamSection::Spectral,
        1.0,
        0.25,
        4.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::SpectralFineTuneCents,
        "spectral_fine_tune_cents",
        "Spectral Fine Tune",
        ParamSection::Spectral,
        0.0,
        -100.0,
        100.0,
        ParamUnit::Cents,
        true,
        None,
    ),
    spec(
        ParamId::AdditiveLevel,
        "additive_level",
        "Additive Level",
        ParamSection::Source,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::AdditivePartialCount,
        "additive_partial_count",
        "Additive Partials",
        ParamSection::Source,
        6.0,
        4.0,
        8.0,
        ParamUnit::Indexed,
        true,
        None,
    ),
    spec(
        ParamId::AdditiveHarmonicSpread,
        "additive_harmonic_spread",
        "Additive Harmonic Spread",
        ParamSection::Source,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::AdditiveOddEvenBalance,
        "additive_odd_even_balance",
        "Additive Odd/Even",
        ParamSection::Source,
        0.0,
        -1.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::AdditiveInharmonicity,
        "additive_inharmonicity",
        "Additive Inharmonicity",
        ParamSection::Source,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::AdditiveSpectralTilt,
        "additive_spectral_tilt",
        "Additive Spectral Tilt",
        ParamSection::Source,
        0.0,
        -1.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::AdditiveRandomDetuneCents,
        "additive_random_detune_cents",
        "Additive Random Detune",
        ParamSection::Source,
        0.0,
        0.0,
        35.0,
        ParamUnit::Cents,
        true,
        None,
    ),
    spec(
        ParamId::Osc1Bandlimit,
        "osc1_bandlimit",
        "Osc1 Bandlimit",
        ParamSection::Oscillator1,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
    spec(
        ParamId::Osc2Bandlimit,
        "osc2_bandlimit",
        "Osc2 Bandlimit",
        ParamSection::Oscillator2,
        0.0,
        0.0,
        1.0,
        ParamUnit::Normalized,
        true,
        None,
    ),
];

pub fn all_params() -> &'static [ParamSpec] {
    &PARAM_SPECS
}

pub const fn macro_param_id(macro_id: MacroId) -> ParamId {
    match macro_id {
        MacroId::Gravitacija => ParamId::GravitacijaMacro,
        MacroId::Bloom => ParamId::BloomMacro,
        MacroId::Heat => ParamId::HeatMacro,
        MacroId::Ruin => ParamId::RuinMacro,
        MacroId::Swarm => ParamId::SwarmMacro,
    }
}

pub fn param_spec(id: ParamId) -> &'static ParamSpec {
    &PARAM_SPECS[id as usize]
}

pub fn param_by_key(key: &str) -> Option<ParamId> {
    PARAM_SPECS
        .iter()
        .find(|spec| spec.key == key)
        .map(|spec| spec.id)
}

#[cfg(test)]
mod tests {
    #![allow(clippy::expect_used)]

    use super::*;

    #[test]
    fn macro_specs_round_trip() {
        for macro_id in MacroId::ALL {
            let spec = param_spec(macro_param_id(macro_id));
            assert_eq!(spec.macro_id, Some(macro_id));
            assert_eq!(spec.key, macro_id.key());
        }
    }

    #[test]
    fn registry_order_matches_ids() {
        for (index, spec) in all_params().iter().enumerate() {
            assert_eq!(spec.id as usize, index);
        }
    }

    #[test]
    fn param_lookup_by_key() {
        assert_eq!(
            param_by_key("filter_cutoff_hz"),
            Some(ParamId::FilterCutoffHz)
        );
        assert_eq!(
            param_by_key("performance_aftertouch_to_baklja"),
            Some(ParamId::PerformanceAftertouchToBaklja)
        );
        assert_eq!(param_by_key("not_a_param"), None);
    }

    #[test]
    fn performance_specs_are_normalized_and_host_visible() {
        for id in [
            ParamId::PerformanceVelocityToLevel,
            ParamId::PerformanceVelocityToFilter,
            ParamId::PerformanceAftertouchToGravitacija,
            ParamId::PerformanceAftertouchToBaklja,
            ParamId::PerformanceModWheelToBloom,
            ParamId::PerformanceModWheelToSwarm,
        ] {
            let spec = param_spec(id);
            assert_eq!(spec.section, ParamSection::Performance);
            assert_eq!(spec.unit, ParamUnit::Normalized);
            assert_eq!(spec.min, 0.0);
            assert_eq!(spec.max, 1.0);
            assert!(spec.host_visible);
        }
    }

    #[test]
    fn source_expansion_specs_are_registered_after_existing_params() {
        assert_eq!(param_spec(ParamId::Osc1PulseWidth).key, "osc1_pulse_width");
        assert_eq!(param_spec(ParamId::CrossMixAmount).key, "cross_mix_amount");
        assert_eq!(param_spec(ParamId::SpectralLevel).key, "spectral_level");
        assert_eq!(param_spec(ParamId::AdditiveLevel).key, "additive_level");
        assert_eq!(param_by_key("noise_color"), Some(ParamId::NoiseColor));
        assert_eq!(
            param_by_key("spectral_position"),
            Some(ParamId::SpectralPosition)
        );
        assert_eq!(
            param_by_key("additive_random_detune_cents"),
            Some(ParamId::AdditiveRandomDetuneCents)
        );
        assert_eq!(ParamId::Osc1PulseWidth as usize, 56);
        assert_eq!(ParamId::CrossMixAmount as usize, 88);
        assert_eq!(ParamId::SpectralLevel as usize, 89);
        assert_eq!(ParamId::SpectralFineTuneCents as usize, 94);
        assert_eq!(ParamId::AdditiveLevel as usize, 95);
        assert_eq!(ParamId::AdditiveRandomDetuneCents as usize, 101);
        assert_eq!(ParamId::Osc1Bandlimit as usize, 102);
        assert_eq!(ParamId::Osc2Bandlimit as usize, 103);
        assert_eq!(param_spec(ParamId::NoiseColor).unit, ParamUnit::Indexed);
        assert_eq!(param_by_key("osc1_bandlimit"), Some(ParamId::Osc1Bandlimit));
        assert_eq!(param_by_key("osc2_bandlimit"), Some(ParamId::Osc2Bandlimit));
        assert_eq!(param_spec(ParamId::CrossMixMode).max, 4.0);
        assert_eq!(param_spec(ParamId::SpectralTable).unit, ParamUnit::Indexed);
        assert_eq!(param_spec(ParamId::SpectralRatio).min, 0.25);
        assert_eq!(param_spec(ParamId::AdditivePartialCount).min, 4.0);
        assert_eq!(param_spec(ParamId::AdditivePartialCount).max, 8.0);
        assert_eq!(param_spec(ParamId::AdditiveRandomDetuneCents).max, 35.0);
    }
}
