[package]
name = "mamut-tui"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
crossterm.workspace = true
mamut-engine.workspace = true
mamut-params.workspace = true
mamut-patch.workspace = true
mamut-runtime.workspace = true
ratatui.workspace = true

[lints]
workspace = true
