[package]
name = "mamut-standalone"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
alsa.workspace = true
anyhow.workspace = true
crossbeam-queue.workspace = true
eframe.workspace = true
mamut-dsp.workspace = true
mamut-engine.workspace = true
mamut-params.workspace = true
mamut-patch.workspace = true
midir.workspace = true
rtrb.workspace = true
serde.workspace = true
toml.workspace = true

[lints]
workspace = true
